apiVersion: v1
kind: Pod
metadata:
  name: nginx-replicaset
  labels:
    app: nginx-app
    type: webserver
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
          - containerPort: 80